include: package:flutter_lints/flutter.yaml

# Enable custom_lint for riverpod_lint rules.
analyzer:
  plugins:
    - custom_lint

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
