// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5loWE4eQZC3MtNiU8YcU71bSdpYJ25D0',
    appId: '1:579327926276:web:30b4559738b7ff2d1cd551',
    messagingSenderId: '579327926276',
    projectId: 'ikiot-70cce',
    authDomain: 'ikiot-70cce.firebaseapp.com',
    storageBucket: 'ikiot-70cce.firebasestorage.app',
    measurementId: 'G-WRD4PQCQVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIH9L2O29UKsbtvYR78tD7LtVHra_l4ww',
    appId: '1:579327926276:android:9f8aa59295d221cf1cd551',
    messagingSenderId: '579327926276',
    projectId: 'ikiot-70cce',
    storageBucket: 'ikiot-70cce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDubsEXSj2zrzVwSaX4YnqVPKlNv_17s4',
    appId: '1:579327926276:ios:a35e95be4c451c2c1cd551',
    messagingSenderId: '579327926276',
    projectId: 'ikiot-70cce',
    storageBucket: 'ikiot-70cce.firebasestorage.app',
    iosClientId: '579327926276-0qqgebkssbb38v8q73v6kstqdogossl9.apps.googleusercontent.com',
    iosBundleId: 'com.ikiotms.ikiotmsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDubsEXSj2zrzVwSaX4YnqVPKlNv_17s4',
    appId: '1:579327926276:ios:a35e95be4c451c2c1cd551',
    messagingSenderId: '579327926276',
    projectId: 'ikiot-70cce',
    storageBucket: 'ikiot-70cce.firebasestorage.app',
    iosClientId: '579327926276-0qqgebkssbb38v8q73v6kstqdogossl9.apps.googleusercontent.com',
    iosBundleId: 'com.ikiotms.ikiotmsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5loWE4eQZC3MtNiU8YcU71bSdpYJ25D0',
    appId: '1:579327926276:web:69e62faeb618f7261cd551',
    messagingSenderId: '579327926276',
    projectId: 'ikiot-70cce',
    authDomain: 'ikiot-70cce.firebaseapp.com',
    storageBucket: 'ikiot-70cce.firebasestorage.app',
    measurementId: 'G-5X57WZRS4W',
  );
}
